server:
  port: 24003
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
#    hibernate:
#      naming:
        #隐式命名规则，以组件路径命名。
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:24000
