server:
  port: 24003
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create-drop
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:24000
logging:
  level:
    cn:
      xialugui: debug
axon:
  serializer:
    events: jackson
