server:
  port: 24003
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create-drop
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  security:
    oauth2:
      resourceserver:
        jwt:
          #          系统信息领域作为资源服务器，使用认证服务器验证jwt
          issuer-uri: http://localhost:24000
logging:
  level:
    cn:
      xialugui: debug
#领域事件的序列化使用jackson而不是默认的xstream，
#xstream是将对象序列化为xml文件的技术，xml文件
#相对json来说过于臃肿，在领域事件的序列化上使用
#jackson较适合。xstream在某些应用场景存在优势
#此处暂不详述。
axon:
  serializer:
    events: jackson
